name: Check Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report
          coverage html

      # TODO update the minimum requirement coverage to 90% after POD-2632 is complete
      - name: Enforce minimum coverage %
        run: |
          coverage report --fail-under=70

      - name: Generate coverage report (XML)
        run: coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true
